replicaCount: 1
restartPolicy: Never

image:
  repository: nginx
  tag: 1.11.0
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: NodePort
  port: 8888
  nodePort: ""

podAnnotations: {}
resources: {}
nodeSelector: {}